### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mondeja** [mondeja/leptos-fluent#205]
## v0.2

- [x] When Leptos v0.7 is released, make leptos-fluent compatible (#228).
- [x] Preserve HTML tag attributes on SSR:
  - #211
  - #228 
- [x] Drop `json` feature from default ones:
  - #214
  - #227
- [x] Single curly braces for `leptos_fluent!` macro:
  - #223
  - #225
  - #244
- [x] Remove `leptos_fluent::SsrHtmlTag` component:
  - #206
  - #224 
  - #226
