### ISSUE TITLE
Language from session storage

### ISSUE THREAD

**Issue by mondeja** [mondeja/leptos-fluent#238]
Just to match with [i18next implementation](https://github.com/i18next/i18next-browser-languageDetector).

### TODO

- [x] `sessionstorage_key` (#294)
- [x] `initial_language_from_sessionstorage` (#294)
- [x] `set_language_to_sessionstorage` (#294)
- [x] `initial_language_from_sessionstorage_to_cookie` (#294)
- [x] `initial_language_from_sessionstorage_to_server_function` (#294)
- [x] `initial_language_from_sessionstorage_to_localstorage` (#294)
- [x] `initial_language_from_localstorage_to_sessionstorage` (#294)
- [x] `initial_language_from_url_param_to_sessionstorage` (#298)
- [x] `initial_language_from_url_path_to_sessionstorage` (#298)
- [x] `initial_language_from_cookie_to_sessionstorage` (#298)
- [x] `initial_language_from_navigator_to_sessionstorage` (#294)
